site_name: spotify-cover-maker
site_url: https://spotify-cover-maker.bootleg.technology
repo_url: https://github.com/nint8835/spotify-cover-maker
repo_name: nint8835/spotify-cover-maker
edit_uri: edit/main/site/docs/
extra:
  social:
    - icon: material/mastodon
      link: https://hachyderm.io/@nit
    - icon: material/github
      link: https://github.com/nint8835
copyright: Copyright &copy; 2023 Riley Flynn

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: teal
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: material/album
    repo: material/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - navigation.tabs
    - navigation.indexes

    - search.suggest

plugins:
  - privacy
  - search
  - social

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Commands:
      - commands/index.md
      - fonts: commands/fonts.md
      - generate: commands/generate.md
  - Configuration:
      - covers.yaml: config/covers.yaml.md
      - Covers:
          - config/covers/index.md
          - Gradient: config/covers/gradient.md